/*
 * This source file was generated by the Gradle 'init' task
 */
package projeto_final;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
 * Testes básicos para a classe App.
 * 
 * @author Projeto Final MC322
 * @version 1.0
 */
class AppTest {
    @Test 
    void appExists() {
        App app = new App();
        assertNotNull(app, "App deve ser criado");
    }
}
